version: "3.9"

services:
  narasihistorian.app.postgres:
    image: postgres:17.2
    container_name: narasihistorian.Database
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # tell postgres to also create the test database
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_DB},${POSTGRES_DB_TEST}

    volumes:
      - pgdata:/var/lib/postgresql/data
      # script that creates multiple databases
      - ./docker/init-multiple-db.sh:/docker-entrypoint-initdb.d/init-multiple-db.sh

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
